In [2]:
!pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu122

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu122


In [3]:
!pip install torchviz

Lets consider 

z = x * y + y^2

The partial derivative of z 

w.r.t x dz/dx = y

w.r.t y dz/dy = x + 2y

given x = 2 and y = 3

dz/dx = 3
dz/dy = 8

In [7]:
import torch

In [ ]:


x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)

z = x * y +  y**2 
print(z)

print(x.grad, y.grad)

# backward pass doesn't return anything!
z.sum().backward()

print(x.grad, y.grad, z.retain_grad())
print(z.detach())

tensor([20., 35., 54.], grad_fn=<AddBackward0>)
None None
tensor([4., 5., 6.]) tensor([ 9., 12., 15.]) None
tensor([20., 35., 54.])


In [16]:
from torchviz import make_dot

dot = make_dot(z, params=dict(x=x, y=y, z=z))
dot.render("z", format="png")

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH